// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for Currency.
const (
	CurrencyEur Currency = "EUR"
	CurrencyMxn Currency = "MXN"
	CurrencyUsd Currency = "USD"
)

// Currency defines model for Currency.
type Currency string

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// NewRefreshTask defines model for NewRefreshTask.
type NewRefreshTask struct {
	Base    Currency `json:"base"`
	Counter Currency `json:"counter"`
}

// Quote defines model for Quote.
type Quote struct {
	Ratio float64 `json:"ratio"`
	Time  string  `json:"time"`
}

// RefreshTask defines model for RefreshTask.
type RefreshTask struct {
	Id *int64 `json:"id,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4yQz0/6QBDF/5f3/R634WI89KocJRElMTHELGVaVtkfzs4qhPR/N1sqVSCGSzPTnfc+",
	"L2+HytvgHTmJKHeI1Yqs7sabxEyu2uaZXLIonzGeTaEwe7iFwt3TBHMF2QZCiShsXAOFTZGPiw/NTluK",
	"WVX1Ti+UGGpYU1z+XO3GYd4qjJk9Z2pgH4jFUJfHUoy6oTz+ZratAtN7MkzLjPs+HML5xStVglZhQp9T",
	"qpni6lHHt1PIQseO8J+pRol/o6GeUd/N6FBMq1D55IT4cslR1o432JyLfJ+80GlS1mJ8HjZF44teVa+9",
	"luurLBNjL+hq79Jfn6P/2ZZZ5m/t2WpBCeMy+2BinFBD3DGPfPMv42qP0qX1WsEHcjoYlIBC0LKK+5f2",
	"KwAA///pZTDkoAIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
