// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package models

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for Currency.
const (
	CurrencyEur Currency = "EUR"
	CurrencyMxn Currency = "MXN"
	CurrencyUsd Currency = "USD"
)

// Currency defines model for Currency.
type Currency string

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// NewRefreshTask defines model for NewRefreshTask.
type NewRefreshTask struct {
	From Currency `json:"from"`
	To   Currency `json:"to"`
}

// RefreshTask defines model for RefreshTask.
type RefreshTask struct {
	Id *int32 `json:"id,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4yQQU86MRDFv8v7/48lJHrrVTnKASUxMcTU3Vm2Sqd12lUI6Xc3rYRVMYbTzLSvb359",
	"ezTeBc/EKULvEZuenKnt1SBC3OxKTzw46AfMlgsoLG+voXBzP8dKIe0CQSMmsbyGwnZSxJM3I2wcxfKq",
	"OTg90iBQ4zjE9uvotoxVVpiJeClbg/hAkixVnsa3VGrnxZkEDcvp8gJHAsuJ1iTICo5iNOuq/o6Xs4LQ",
	"62CF2kpWPEf9+B3/9ExNKl5zel9QJxT7OxNfTrE68a7U/0IdNP5Nx0CnhzSnxyizQvLnq3/Q1lXV4TfQ",
	"Pylte1Z0+cS3HFnuPDQPm42CD8QmWGhAIZjUx8+b/BEAAP//lwYyI0oCAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
