openapi: "3.0.0"
info:
  version: 1.0.0
  title: Quotes
  description: Test assignment
  contact:
    name: Zakhar Eliseev
    url: http://github.com/ZakharE
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
paths:
  "/quote":
    get:
      description: returns last value for quote
      operationId: getLastQuote
      parameters:
        - name: baseCurrency
          in: query
          description: base currency
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]{3}$'
        - name: counterCurrency
          in: query
          description: counter currency
          required: true
          schema:
            type: string
            pattern: '^[a-zA-Z]{3}$'

      responses:
        '200':
          description: current quote value with time at which this quote is valid
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/QuoteData'
        '404':
          description: returns if no data available at the moment, i.e no refresh task were executed
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'
        'default':
          description: error with description
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'


  "/quote/task/{id}":
    get:
      description: returns a task
      operationId: getTask
      parameters:
        - name: id
          in: path
          description: ID of task to fetch
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: task response
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/QuoteData'
        '404':
          description: returns if task with specified id doesn't exist
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'
        '425':
          description: returns if task exists, but was not processed yet
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/TaskResponseError'

        'default':
          description: error with description
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'



  "/quote/task":
    post:
      description: Create task for quote refreshing
      operationId: refreshQuote
      requestBody:
        description: Currency pair which to refresh
        required: true
        content:
          application/json:
            schema:
              $ref: './models/models.yaml#/components/schemas/NewRefreshTask'
      responses:
        '200':
          description: task response
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/RefreshTask'
        '400':
          description: error if currency are in the 'base' and in the 'counter' are the same
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: './models/models.yaml#/components/schemas/Error'